### ISSUE TITLE
StringLocalizerFactory assumes that the default namespace is the same as the application name when resourcePath is specified

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Localization#244] opened 2016-05-16 03:39 UTC
Steps:

1. Create an application named App1
2. Add `.AddViewLocalization(options => options.ResourcesPath = "custom-dir")` to Startup
3. Add a resource under custom-dir named `Controllers.HomeController.resx` and verify that the `IHtmlLocalizer<HomeController>` correctly works for `App1.Controllers.HomeController`.
4. Change the namespace for the controller to `App2.Controllers.HomeController` and see it fail to locate it.

Kinda obscure scenario I ran into when I tried copying the Controller from release verification to a different app.

Expected:
Perhaps an option to to specify the default namespace and for the resource to continue to be located.

**Comment by hishamco** [comment] 2016-05-16 06:47
I think it's duplicate or related to the issue #157

**Comment by Eilon** [comment] 2016-07-07 17:45
@ryanbrandenburg please see if this is a dup of the other bug.

**Comment by ryanbrandenburg** [comment] 2016-07-08 00:03
This is a [documented](https://docs.asp.net/en/latest/fundamentals/localization.html#resource-file-naming) edge case.  If you're resource isn't in the main namespace for your project you must specify the entire namespace. So from your example `Controllers.HomeController.resx` would become `App2.Controllers.HomeController.resx`. We allow the base namespace to be left off the to prevent excessively long names or nested folders, but to prevent collisions you must specify the namespace of anything else.

How do you feel about that behavior? It's not my favorite thing, but I can't come up with any better solutions, so I'm open to input.

**Comment by pranavkm** [comment] 2016-07-08 00:07
> If you're resource isn't in the main namespace for your project you must specify the entire namespace.

I think in this case it was the inverse. The resource was in the base namespace, the controller (`TType` for `IHtmlLocalizer<TType>` ) wasn't. I think I might've spent less figuring out this issue if https://github.com/aspnet/Localization/issues/258 is addressed.

**Comment by Eilon** [comment] 2016-07-08 04:46
@ryanbrandenburg can you discuss with @DamianEdwards if necessary as well?

**Comment by ryanbrandenburg** [comment] 2016-07-08 17:52
Sorry @pranavkm I was being confusing, I meant 

> If you're .cs file isn't in the main namespace for your project you must specify the entire namespace on the resource.

I talked with @DamianEdwards in person, he agrees with me that this is expected behavior.

**Comment by ryanbrandenburg** [comment] 2016-07-11 22:28
Since nobody seems to be objecting I'll close this one out, feel free to re-open if there's new or missing info.

**Closed by ryanbrandenburg** 2016-07-11 22:28 UTC
Labels: 1 - Ready, bug
