### ISSUE TITLE
Localization no longer works after updating to rc1

### ISSUE THREAD

**Issue by damienbod** [aspnet/Localization#150] opened 2015-11-18 19:19 UTC
https://github.com/damienbod/AspNet5Localization

Greetings Damien

**Comment by hishamco** [comment] 2015-11-18 19:39
It works fine .. what's the issue you are facing?

**Comment by damienbod** [comment] 2015-11-18 19:58
Does not localize the string anymore, console, or in VS

Result is Name (key) instead of for example name it-CH

Greetings Damien

**Comment by hishamco** [comment] 2015-11-18 20:27
I'll check your source later

**Comment by damienbod** [comment] 2015-11-18 20:27
Thanks

**Comment by hishamco** [comment] 2015-11-18 20:29
Can you let me know which dnx version you are using?

**Comment by damienbod** [comment] 2015-11-18 20:52
1.0.0-rc1-final clr x86 win

Greetings Damien

**Comment by hishamco** [comment] 2015-11-18 22:16
Why you didn't switch to rc2, because I faced another issue in previous versions have a look #147

**Comment by damienbod** [comment] 2015-11-19 07:40
Hi @hishamco 
Thanks for your reply. 

I used rc1 because it was released yesterday. Are you saying rc1 has a problem?

Greetings Damien

**Comment by hishamco** [comment] 2015-11-19 16:45
@damienbod I run the localization sample, and it works fine, are you sure there's no missing piece in your app?

**Comment by danroth27** [comment] 2015-11-19 17:12
@ryanbrandenburg Can you please take a look?

**Comment by damienbod** [comment] 2015-11-19 19:56
@hishamco, not that I know of.
 
The following URL is no longer localized since the update to rc1

http://localhost:5000/api/about?culture=it-CH

DataAnnotations localization still works.

All I did was update the project.json, changed the Startup.cs with the breaking changes. You can see this in the history. If I downgrade to beta8, it works.

I also tried upgrading to rc2 with no success. Tested in the console.

Thanks for your help

Greetings Damien

**Comment by hishamco** [comment] 2015-11-19 20:30
Now I will clone the repo and test it

**Comment by hishamco** [comment] 2015-11-20 04:14
Seems it doesn't work as expected, can you let me know the latest dnx version where you got the right result?

**Comment by damienbod** [comment] 2015-11-20 05:33
Hi @hishamco 

Version 1.0.0-beta8 works as expected. Got it from NuGet (released version)

Greetings Damien

**Comment by hishamco** [comment] 2015-11-20 13:22
I'm not sure if the issue is cause by #138, but seems @ryanbrandenburg will investigate into this

**Comment by Thetyne** [comment] 2015-11-21 15:32
Reproduce in rc1 with https://github.com/damienbod/AspNet5Localization, my own test and https://github.com/aspnet/Localization/tree/dev/samples/LocalizationSample.
i test later with a IStringLocalizerFactory.

**Comment by hishamco** [comment] 2015-11-21 15:37
Even I it doesn't localize anything, but localization sample works fine, i'm not sure if this related to #138 as I mentioned before or there's a bug in mvc localization

**Comment by Thetyne** [comment] 2015-11-21 15:45
in beta8, culture and uiculture is correct
- when i debug in vs 2015 it's don't change resx file with culture.
- when i use dnx web command, it's ok.

In rc1 no resx found when i use IStringLocalizer and HtmlLocalizer.
you can see this problem inside my web stream : https://www.livecoding.tv/video/frbodibuilding-report-website-mobile-app-2/

**Comment by ryanbrandenburg** [comment] 2015-11-24 00:01
There are a couple things happening here. One is that the convention you're using doesn’t work well with IHtmlLocalizer. Check out https://github.com/aspnet/Mvc/tree/dev/test/WebSites/LocalizationWebSite for an example of the new way. Basically now instead of having "IHtmlLocalizer<AmazingResource>" You want to do "IHtmlLocalizer<AboutController>" and have your resource as "AspNet5Localization.Controllers.AboutController.<lang>.resx". It is POSSIBLE to do the "AmazingResource" method, but it's not recommended.

Another part of this is that it's no longer recommended to have a "Default.resx". Instead the "key" of the resource should be the default value for it. So instead of having "Greeting" with a value in the default resx of "Hello" the key is "Hello", which will be returned if no matching language is found.

Also for what @Thetyne is talking about, where VS will not localize properly because the resources aren't handled correctly, that's tracked here https://github.com/aspnet/dnx/issues/3047

**Comment by hishamco** [comment] 2015-11-24 06:19
@ryanbrandenburg you are right that's the pattern that we should follow, but if the resource file resident with that same place of the controller issue #138 will happen

**Comment by damienbod** [comment] 2015-11-24 07:34
Hi @ryanbrandenburg 

Thanks for your answers.

So you’re saying if you want to use the new localization, you have to name the resource like the controller with this magic string.

Not very nice, or developer friendly.

I then need to have one resx per controller. So for an application with a 100 controllers and 3 languages I would have 300 resource files. 

This would be a nightmare.

Your recommendation that the key is the default value. This does not work for most of the applications which I am involved in.

Most company’s program in English. Most of our applications are translated into de-CH, fr-CH and it-CH, we usually have no default English view. (Switzerland). The default key nearly never matches the default localization. 

We do not translate the application ourselves, we usually send the keys as a single file to a separate company which translates this for us. This is usually sent as a csv or excel file. This has to be imported and exported so if I have a lot of separate resource files, this costs too much.

This issue should be a bug, because it does not work and the linked issue is closed. At present in rc1, this does not work.

Maybe you could considered rewriting the use cases for MVC 6 localization, because if it is released as it is, recommended, it will be unusable for most of our applications and for many other company’s which deal in localization regularly. It would mean that I have to re-implement localization, if I want to use ASP.NET 5 for my clients.  

Thanks and greetings Damien

**Comment by joeaudette** [comment] 2015-11-24 15:01
@damienbod wrote "I then need to have one resx per controller. So for an application with a 100 controllers and 3 languages I would have 300 resource files."

I have found that I can create an empty class in my web app, say I name it LocalizationWebSite.Components.SharedResources.cs
This class has no properties or methods.
Then take a dependency of 

    IHtmlLocalizer<SharedResources> 

in my controller and I can localize strings from a resx file named

    LocalizationWebSite.Components.SharedResources.fr.resx

This file lives in the /Resources folder of the web app which we point to from startup

    services.AddMvc().AddViewLocalization(options => options.ResourcesPath = "Resources");

I could use this in multiple controllers, so we are not forced to use a resx file per controller.

The problem I have at the moment is I can't seem to get it to work if my controller classes or my resource class are in a class library instead of directly in the web app.

If I have a classlibrary named SomeWebLib with a class named CommonResources and in HomeController of the web app I take a dependency on

    IHtmlLocalizer<SomeWebLib.CommonResources> 

in the constructor
I cannot seem to get any localization by having a file named
SomeWebLib.CommonResources.fr.resx in the webapp Resources folder

I'm using kestrel from the command line to avoid the known VS 2015 issues. I'm setting my browser language to French while testing.
The project I'm testing with is here and is just a modified version of the LocalizationWebSite project from the mvc repo tests:
https://github.com/joeaudette/experiments

I don't know if these limitations are expected or whether to consider them bugs or whether there is some other approach I'm supposed to use if my controllers and/or resources are in a classlibrary instead of directly in the web app.

**Comment by ryanbrandenburg** [comment] 2015-11-24 20:49
@damienbod, @joeaudette 's suggestion should work for re-using the resource.

As for using the default value as the key, you should be able to use the old style of key selection, just know that if it doesn't find a resource for the given key and culture it will default to using the key given. So if your key was "greeting" and you didn't have that set for fr-CH your page would show "greeting".

@joeaudette your class library thing sounds like a separate thing, please feel free to file it as a new issue.

I think that's everything @damienbod so I'm closing this issue, but let us know if we missed something or you have further questions.

**Closed by ryanbrandenburg** 2015-11-24 20:49 UTC
Labels: 2 - Working, investigate

**Comment by damienbod** [comment] 2015-11-24 21:15
Hi @ryanbrandenburg 

Thanks for your answer. It should be possible to use a Shared resource without having to create an empty class. Hopefully this is not the recommended way to use shared resources.

This is not a good solution, but as least it works. So if I create ten shared resources, I need ten emtpy classes in the project to use the resx. 

@joeaudette Thanks for the workaround.

As a developer, it should be possible to define how resource files are named and also where the resources are are saved.

Greetings Damien

**Comment by ryanbrandenburg** [comment] 2015-11-24 23:05
It is also an option to implement your own IStringLocalizerFactory and/or IStringLocalizer with your expected behavior.

**Comment by joeaudette** [comment] 2015-11-25 13:50
I've opened a [new issue here about the problem localizing controllers that live in a classlibrary](https://github.com/aspnet/Localization/issues/152)

**Comment by Thetyne** [comment] 2015-11-26 18:19
@ryanbrandenburg thanks for reply.

I have implement IStringLocalizerFactory and IStringLocalizer for read json file and it's work perfectly.

**Comment by jmurkoth** [comment] 2015-11-29 16:39
@joeaudette  @damienbod  .. Ran into the same issue as you did and the work around of using an empty class doesn't seem to work when you are using Data annotation to drive model validation in the view
I took @damienbod 's example and added a view to illustrate the problem. Code is available here
https://github.com/jmurkoth/LocalizationIssue .
Get the following error
System.InvalidOperationException' in mscorlib.dll ("The resource type 'AspNet5Localization.Resources.AmazingResource' does not have an accessible static property named 'BoxLengthRequired'

**Comment by ryanbrandenburg** [comment] 2015-12-01 00:04
@jmurkoth it looks like you're using the "Old" style of Resource selection [with 'ErrorMessageResourceType'](https://github.com/jmurkoth/LocalizationIssue/blob/master/src/AspNet5Localization/Model/Box.cs#L14). You're perfectly welcome to do that, but it won't go through the new system which all the Empty class stuff above is intended to work with. If you want to use "ErrorMessageResourceType" you'll have to point it at an old-school "Designer" class. If that doesn't solve you or you run into something else feel free to open a new issue.

**Comment by damienbod** [comment] 2015-12-01 07:47
@joeaudette @hishamco @danroth27 @Thetyne @jmurkoth  I've just created a global issue for this, my you could give your views here

https://github.com/aspnet/Home/issues/1142

Greetings Damien
