### ISSUE TITLE
zh-TW should fallback to zh-Hant before zh

### ISSUE THREAD

**Issue by luciusli** [aspnet/Localization#273] opened 2016-08-05 09:12 UTC
zh-CN should also fallback to zh-Hans.

**Comment by Eilon** [comment] 2016-08-05 17:26
I have a feeling that the logic is quite simple: It just chops off the last segment of the locale string after the `-` character and uses that. I don't think any part of the system actually knows anything about which languages are "related" to other languages.

@ryanbrandenburg do you know any more about how this fallback logic works?

**Comment by hishamco** [comment] 2016-08-05 18:04
As @Eilon said zh-TW & zh-Hant should fallback to zh, I never seen a framework to do such thing, because you need something in advance (relation between the languages),

**Comment by ryanbrandenburg** [comment] 2016-08-05 22:47
Actually, we use `CultureInfo.Parent` to walk down the hierarchy rather than string manipulation.

For zh-TW in net451 (there are some differences between frameworks) the hierarchy goes "zh-TW->zh-CHT->zh-Hant->zh" in netcoreapp1.0 it's the same, but omit "zh-CHT". Either framework should reach zh-Hant before zh. The most likely cause of skipping it would be that zh-TW or zh-Hant are not among `SupportedCultures` or `SupportedUICultures`. If zh-TW and zh-Hant are both in your `SupportedCultures` and `SupportedUICultures` and you are still encountering this problem please upload a reproduction app as a GitHub repository so that I can diagnose the problem.

**Comment by Eilon** [comment] 2016-08-05 22:56
This seems like a complete explanation. Assuming the steps in @ryanbrandenburg 's response are followed, there is no further issue here, so I'm closing the issue.

If the ultimate issue is that the hierarchy of cultures on .NET Core (netcoreapp) is undesirable, please file a new bug at https://github.com/dotnet/corefx/issues/. Thanks!

**Closed by Eilon** 2016-08-05 22:56 UTC

**Comment by yufeih** [comment] 2017-09-14 06:57
@ryanbrandenburg 

> Actually, we use CultureInfo.Parent to walk down the hierarchy rather than string manipulation.

It is actually using a simple string manipulation here: https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L206

> If zh-TW and zh-Hant are both in your SupportedCultures and SupportedUICultures and you are still encountering this problem please upload a reproduction app as a GitHub repository so that I can diagnose the problem.

I prepared a [PR](https://github.com/aspnet/Localization/pull/416/files) with a test case to reproduce the problem
