### ISSUE TITLE
In beta8 localize resource cannot be loaded

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Localization#68] opened 2015-09-08 03:16 UTC
In latest beta 8 15585, localized resources (*.resx) are not embedded in a single assembly any more; instead they are put in sub-folders as in normal desktop applications, for an example: \en-AUS\xapp.xtype.resources.dll. But ResourceManagerStringLocalizer still assumes all resources are in one assembly (xapp.dll) currently like in beta 7 or eariler.

**Comment by kirthik** [comment] 2015-09-11 21:45
@xatabhk : Locale specific resources get embedded to locale specific satellite assemblies. That is the right way. ResourceManagerStringLocalizer just calls `ResourceManager.GetString`. `ResourceManager` understands satellite assemblies. 

Could you please tell me what issue you are seeing and please provide a repro too if possible.

**Comment by xatabhk** [comment] 2015-09-11 23:40
I assumed ResourceManager understanding satellite assemblies too; but it did and does not. It seems no actual *.resx files have been tested before as no *.resx file use in the sample.

My test results:
1. Locale specific resources do not get embedded to locale specific satellite assemblies before beta7 WebTools installed.
Before that, all Locale specific resources are put in one single DLL.

2.ResourceManager does not understands satellite assemblies actually. It  and ResourceManagerStringLocalizer assume all resources are in one DLL just like in previous beta versions. 

Steps to reproduce this issue:
1. Install beta7 WebTools for VS.
   Beta7 WebTools must be used for reproducing the bug as beta5 & 6 WebTools don’t produce satellite assemblies no matter how many local resources added.
2. Add some *.resx files to the sample.
3.Run the sample, you will notice ResourceManagerStringLocalizer loads default resource always not matter which language you choose.

**Comment by kirthik** [comment] 2015-09-12 00:02
Your statement "Before that, all Locale specific resources are put in one single DLL." is not true.

In beta7 and earlier, `ResourceManagerStringLocalizer` loaded default resource always since underlying dnx did not understand resources or locale satellite assemblies. Dnx did not embed locale specific resources in the main assembly. It just ignored them which is why default resource got loaded always. In beta-8 milestone, we added support in dnx to generate resources for satellite assemblies. 

We are still working on getting the end-to-end story working across Localization. Once we have everything working, I will add a sample to this repo.

**Comment by xatabhk** [comment] 2015-09-12 01:29
I say putting in one single DLL because that was what I found when I used Reflector to figure out resource names in main DLL a while ago – after I noticed no satellite DLLs generated. So at least for a time, all locale specific resources did get put in main DLL.

**Comment by kirthik** [comment] 2015-09-14 23:12
Closing this since the change was intentional and by design. Please open a new bug if you run into an issue with this design.

**Closed by kirthik** 2015-09-14 23:12 UTC
Labels: 1 - Ready, bug
