### ISSUE TITLE
Async view localization issue under ubuntu.

### ISSUE THREAD

**Issue by Tekkeitsertok** [aspnet/Localization#225] opened 2016-03-05 11:11 UTC
When localization is called from view directly, it works only if Controller associated method isn't async (under ubuntu 14.04). It works as expected under Windows env but strangely not under linux env.
It uses a custom resource provider. In this demo project, localized strings are added to a dictionary inside Localization/LocalizationService, then through DI, I can access them multiple way (through IViewLocalizer with IStringLocalizer & IStringLocalizerFactory Implementation but also directly from controller with LocalizationService injection)
In this particular example, I access my resource in the controller & in the view to visually see the issue inside the View. I also retrieve CurrentUICulture from controller & from the view to demonstrate that sometime they aren't equal.

## System configuration
- Updated Ubuntu 14.04.
- dotnet cli --version output
```
.NET Command Line Tools (1.0.0-dev-001698)

Product Information:
 Version:     1.0.0-dev-001698
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

## How to reproduce 
```
git clone https://github.com/Tekkeitsertok/Demo.git
cd Demo/src/Demo/
dotnet restore
dotnet build
cp -R appsettings.json project.json Views/ wwwroot/ bin/Debug/netstandardapp1.5/ubuntu.14.04-x64/
dotnet run
```
## Result
Sometimes localized text retrieved from view isn't correct. 
(http://url:5000/Home/Index) :
```
Localized string from View : Localized EN
Localized string from Controller : Localized FR
CurrentUICulture from View : en
CurrentUICulture from Controller : fr
```
should be everytimes (when using fr as default browser language)
```
Localized string from View : Localized FR
Localized string from Controller : Localized FR
CurrentUICulture from View : fr
CurrentUICulture from Controller : fr
```

**Comment by hishamco** [comment] 2016-03-06 21:38
Unfortunately I don't have Ubuntu installed in my laptop, but what I have seen is you are using a custom resource provider, as you mentioned before the behavior is appear in linux, which is strange!! but i have a question why in the [controller](https://github.com/Tekkeitsertok/Demo/blob/master/src/Demo/Controllers/HomeController.cs#L20) you are using ```loc.Get``` while in the [view](https://github.com/Tekkeitsertok/Demo/blob/master/src/Demo/Views/Home/Index.cshtml#L5) you are using ```loc.GetString```? Also can you try the [Localization.StarterWeb](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.StarterWeb) and check if you get the same behavior

**Comment by Tekkeitsertok** [comment] 2016-03-07 09:00
Yes, I'm using a custom resource provider. In this demo, it's a part of a bigger project where localized strings are "cached" on demand to a dictionary from a remote database.
Then, with `IStringLocalizer` & `IStringLocalizerFactory` implementation, I can access them directly through DI with `IViewLocalizer.`
In the controller, I set a viewdata var in order to visually see the issue inside the view. I understand it seems useless to retrieve localized string from controller & from the view, but it's only to prove a point. I also edited sources to add few comments on basic methods & also added a ViewData var to also compare `CurrentUICulture` (from View & Controller).
About the Localization.StarterWeb, I'm currently testing it, but I have few dependencies error under ubuntu (Microsoft.Win32.Registry), I'll solve this and comment back with the result. But from what I've seen from sources, `HomeController` methods aren't async, so it should work without any issue.

**Comment by hishamco** [comment] 2016-03-07 09:09
I see, you can just one of the default ASP.NET default samples if you do so, to check the scenario, perhaps there's an issue in your custom implementation (May Be)
FYI you can have a look to the [Localization.EntityFramework](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.EntityFramework)

**Comment by Tekkeitsertok** [comment] 2016-03-07 14:19
Ok, still using the same Demo project, I copied from [Localization.EntityFramework](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.EntityFramework) Models, `EFStringLocalizer` & `EFStringLocalizerFactory`, modded available cultures to match previous ones (en, fr & pl), changed Startup to now use `EFStringLocalizer`, changed also both view & controller to retrieve the "Hello" localized string. And I still got the same result from time to time :
```
Localized string from View : Hello
Localized string from Controller : Bonjour
CurrentUICulture from View : en
CurrentUICulture from Controller : fr
```

I also updated the [Demo github project](https://github.com/Tekkeitsertok/Demo) with lasts modifications. I'm available if there are any other questions regarding this issue, testings, etc.

**Comment by hishamco** [comment] 2016-03-07 14:49
Seems @ryanbrandenburg will investigate on that, if I have Ubuntu I 'll do it myself .. hope you wait for his reply

**Comment by ryanbrandenburg** [comment] 2016-03-24 19:04
Hey @Tekkeitsertok, could I get you to confirm that this still happens for you while I work on a repro?

**Comment by Tekkeitsertok** [comment] 2016-03-24 19:25
Hello,

I just updated to last RC2 20270 and last dotnet cli available on ubuntu 14.04 and it still happens.
dotnet --version output :
````
.NET Command Line Tools (1.0.0-beta-001984)

Product Information:
 Version:     1.0.0-beta-001984
 Commit Sha:  b8bf086417

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
````
Results are still the same.

**Comment by ryanbrandenburg** [comment] 2016-03-29 00:01
Hey @Tekkeitsertok sorry for the delay, I had trouble getting this set up on my Ubuntu VM.

I can confirm that I was able to reproduce your problem, though I had to mess with the code a little (https://github.com/ryanbrandenburg/Demo/tree/modified). I am still reasoning through to determine whether this is a problem with our code or with the way you're using it however. Offhand it seems suspicious that you're passing a culture into your localizer though (https://github.com/Tekkeitsertok/Demo/blob/master/src/Demo/Localization/DBStringLocalizer.cs#L14).

I will look into it more as I have time, just wanted to let you know I hadn't forgotten about you and give you an update.

**Comment by ryanbrandenburg** [comment] 2016-03-29 18:07
Hey @Tekkeitsertok, it looks like you're using CurrentCulture instead of CurrentUICulture [here](https://github.com/Tekkeitsertok/Demo/blob/master/src/Demo/Localization/EntityFramework/EFStringLocalizer.cs#L51). CurrentUICulture is the one you should be using for localization (language) stuff, whereas CurrentCulture is intended for formatting tasks. When I changed those instanced of CurrentCulture to CurrentUICulture I consistently got the correct results on my VM.

**Comment by Tekkeitsertok** [comment] 2016-03-30 10:35
Hello @ryanbrandenburg, indeed CurrentCulture was used instead of CurrentUICulture. It was taken from here : [EFStringLocalizer](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.EntityFramework/EFStringLocalizer.cs) as suggested.
So, I cloned back your cleaned branch, changed from CurrentCulture to CurrentUICulture in EFStringLocalizer, but still got the same as before... To be sure, i tested on a second ubuntu server, and same behaviour.
I also tested my Custom DBStringLocalizer and got the same. Sometimes it takes 10 or more page refresh to display wrong localization.
dotnet --version output :
1.0.0-beta-002111

I must say, except this small issue, I'm really impressed of what have been done here with the whole new dotnet and aspnet core and didn't encounter any other issue or managed to solve them.

**Comment by ryanbrandenburg** [comment] 2016-04-05 19:52
Hello @Tekkeitsertok, an update here. I did manage to get this to reproduce (and in doing so figured out why I thought switching to CurrentUICulture fixed it). After lots of experimenting it seems that this is caused by dotnet/coreclr/issues/4088, thanks for catching it! We will update this issue when it's resolved.

**Comment by ryanbrandenburg** [comment] 2016-04-07 17:45
This should be resolved the next time we pick up new CoreCLR packages.

**Comment by Tekkeitsertok** [comment] 2016-04-07 17:51
Yes, I followed the other thread. Thank you for that. I think we can close this ?

**Comment by ryanbrandenburg** [comment] 2016-04-08 00:12
Yes, since the other issue is open to track the fix's movement into RC2 I'll close this one.

**Closed by ryanbrandenburg** 2016-04-08 00:12 UTC
Labels: 2 - Working, investigate
