### ISSUE TITLE
CookieRequestCultureProvider slow performance

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/Localization#252] opened 2016-06-02 14:07 UTC
I have detected that if the user select a language and I use the CookieRequestCultureProvider, the site is slower. 

My code: 

               
```
RequestCultureProviders = new List<IRequestCultureProvider>
                {
                    new CookieRequestCultureProvider
                    {
                        CookieName = "_cultureLocalization"
                    },
                    new QueryStringRequestCultureProvider(),
                    new AcceptLanguageHeaderRequestCultureProvider
                    {

                    }

                }
```

If I dont set the language and take default, all is very fast, but if I set and save in cookie, the performance is very slow... 
Any ideas? #

**Comment by hishamco** [comment] 2016-06-03 02:23
Why you need to initialize the ```RequestCultureProviders``` while it's already have the default providers?!!
Can you provide a link to your sample for further investigation

**Comment by chemitaxis** [comment] 2016-06-03 08:50
HI @hishamco Here you have the rest of the code involved in Localization:

```
var requestLocalizationOptions = new RequestLocalizationOptions
            {
                // Set options here to change middleware behavior
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("en-US"),
                     new CultureInfo("fr-FR"),
                     new CultureInfo("pt-PT"),
                     new CultureInfo("pt-BR"),
                     new CultureInfo("it-IT"),
                     new CultureInfo("de-DE"),
                    new CultureInfo("es-ES")
                },
                SupportedUICultures = new List<CultureInfo>
                {
                     new CultureInfo("en-US"),
                     new CultureInfo("fr-FR"),
                     new CultureInfo("pt-PT"),
                     new CultureInfo("pt-BR"),
                     new CultureInfo("it-IT"),
                     new CultureInfo("de-DE"),
                     new CultureInfo("es-ES")

                },
                RequestCultureProviders = new List<IRequestCultureProvider>
                {
                    new CookieRequestCultureProvider
                    {
                        CookieName = "_cultureLocalizationGenially"
                    },
                    new QueryStringRequestCultureProvider(),
                    new AcceptLanguageHeaderRequestCultureProvider
                    {
                        
                    }

                }
            };

            app.UseRequestLocalization(requestLocalizationOptions, defaultRequestCulture: new RequestCulture("en-US"));
```

Do you need any more? Thanks!

**Comment by chemitaxis** [comment] 2016-06-03 19:01
I will add some screen captures showing the differences...

**Comment by chemitaxis** [comment] 2016-06-06 14:28
I have added two screen captures, the same URL (with no caching). The slow has the cookie set, the  fast, no. Tested with Fiddler with Chrome, Safari, Edge and Firefox. Same result. The difference is too big. 

![screen shot 2016-06-06 at 16 24 02](https://cloud.githubusercontent.com/assets/1420409/15825331/92770340-2c03-11e6-8d0c-66d82e5633e9.png)

![screen shot 2016-06-06 at 16 24 37](https://cloud.githubusercontent.com/assets/1420409/15825336/95f3d98a-2c03-11e6-9cc7-63383f5fd8db.png)

@shanselman @hishamco any ideas or help? 

Thanks.

**Comment by hishamco** [comment] 2016-06-10 22:08
sorry @chemotaxis I was sick last few days, my question again why you need to define the culture providers while they are already there?!!
If you need to change the cookie name, please use:
```csharp
CookieRequestCultureProvider.DefaultCookieName = "_cultureLocalization";
```
modify what I said before and have a try

**Comment by chemitaxis** [comment] 2016-06-13 12:04
Hi @hishamco, I solved the problem... It is a problem with Resources files, if you don't have a default resources named like **My.Resources.en-US.resx** where en-US is your default request culture the system works, but it is very slow. 

I had this:
My.Resources.resx
My.Resources.fr-FR.resx
My.Resources.it-IT.resx
My.Resources.pt-PT.resx
My.Resources.pt-BR.resx
My.Resources.de-DE.resx

Now I have this:
My.Resources.resx
My.Resources.en-US.resx
My.Resources.fr-FR.resx
My.Resources.it-IT.resx
My.Resources.pt-PT.resx
My.Resources.pt-BR.resx
My.Resources.de-DE.resx

Is this a bug?

**Comment by hishamco** [comment] 2016-06-22 00:20
I see, nothing but the sample that's provided by this repo is also missing the resource for the default culture. I'm not sure if this related to issue #162 
/cc @Eilon  @ryanbrandenburg

**Comment by Eilon** [comment] 2016-07-08 05:08
@ryanbrandenburg let's see if we can repro this and perhaps run in a profiler to see what's taking so long.

**Comment by hishamco** [comment] 2016-07-08 05:44
@chemitaxis I'd like to inform you that the default resource issue is mentioned in the issue #257 too, hope the @ryanbrandenburg fix will solve the issue

**Comment by ryanbrandenburg** [comment] 2016-07-11 22:15
@chemitaxis how slow were you seeing it? While I haven't actually profiled this, when replicating it in `samples\LocalizationSample` I didn't see a noticeable difference in speed between a missing and an existing Language. Does this still reproduce for you when using our latest packages? If it does, can you upload a complete minimum reproduction app to a GitHub repo?

**Comment by ryanbrandenburg** [comment] 2016-07-15 16:54
Closing this one out as could not reproduce. If you still run into this please reopen with a reproduction repo.

**Closed by ryanbrandenburg** 2016-07-15 16:54 UTC
Labels: 1 - Ready, bug, perf

**Comment by chemitaxis** [comment] 2016-07-15 17:04
Ok, close, but the problem persist, in Azure Web App. Thanks for all. ;)
Best.

2016-07-15 18:54 GMT+02:00 Ryan Brandenburg <notifications@github.com>:

**Comment by ryanbrandenburg** [comment] 2016-07-15 19:13
I'm not able to replicate your described behavior, even on an Azure Web App. Likely there's another factor which hasn't been mentioned here contributing to your problem. It would help me to find that factor and reproduce your problem if you could provide an entire project which exhibits the behavior (as a GitHub repo). If you can provide me with that I will investigate further.

**Comment by chemitaxis** [comment] 2016-07-15 22:42
Ok, I will try this weekend... Thank you so much for your time... And sorry if I was rude... It dit not intend. Best.

**Comment by Ponant** [comment] 2017-02-07 11:03
Hi @hishamco , 
I am trying to set the default culture cookie name and came across your suggestion of setting
`CookieRequestCultureProvider.DefaultCookieName = "_cultureLocalization";`

But how can this work with a static readonly?

In a controller-action, the following works
`                Response.Cookies.Append(
                 CookieRequestCultureProvider.DefaultCookieName,
                 CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)),
                 new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });` 
but otherwise setting the name does not work
`                Response.Cookies.Append(
                 "myCookie",
                 CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)),
                 new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });`
Please advise if possible
