### ISSUE TITLE
Beta 8 Load Resource Assembly Cause Exception System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by luchen1021** [aspnet/Localization#123] opened 2015-10-20 13:02 UTC
Beta 8 load resource assembly cause exception System.IO.FileNotFoundException.  The resource assembly is defined in legacy .NET class library, not DNX class library.  The same solution works for Beta 7 but fails when using Beta 8.
Beta 8 Solution
https://github.com/luchen1021/AspNet5Beta8Resource.git
https://github.com/luchen1021/AspNet5Beta8Resource
Beta 7 Solution
https://github.com/luchen1021/AspNet5Beta7Resource.git
https://github.com/luchen1021/AspNet5Beta7Resource

Change project reference to binary reference for Legacy Library and Legacy Resource Library.
https://github.com/luchen1021/AspNet5Beta8ResourceBinaryReference.git
https://github.com/luchen1021/AspNet5Beta8ResourceBinaryReference
Running in Visual Studio 2015 with IISExpress still get the same exception as shown in top comment.
Publish works fine in binary reference approach. After deploying the published output to IIS (not IIS express), it works fine without any exception.

Exception Detail:
System.IO.FileNotFoundException: {"Could not find file 'AspNet5Beta8Resource.LegacyResources.resources'.":null}
Data: {System.Collections.ListDictionaryInternal}
FileName: null
FusionLog: null
HResult: -2147024894
HelpLink: null
IPForWatsonBuckets: {1858045768}
InnerException: null
IsTransient: false
Message: "Could not find file 'AspNet5Beta8Resource.LegacyResources.resources'."
RemoteStackTrace: null
Source: "mscorlib"
StackTrace: " at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
at AspNet5Beta8Resource.LegacyResources.Properties.Resources.get_Title() in D:\Project\GitHub\AspNe
t5Beta8Resource\AspNet5Beta8Resource.LegacyResources\Properties\Resources.Designer.cs:line 68
at AspNet5Beta8Resource.LegacyLibrary.LegacyClass.GetTitle() in D:\Project\GitHub\AspNet5Beta8Resource\AspNet5Beta8Resource.LegacyLibrary\LegacyClass.cs:line 14
at AspNet5Beta8Resource.DnxWebHost.Controllers.ValuesController.Get() in D:\Project\GitHub\AspNet5Beta8Resource\AspNet5Beta8Resource.DnxWebHost\Controllers\ValuesController.cs:line 21"
TargetSite: {System.Reflection.RuntimeAssembly InternalGetSatelliteAssembly(System.String, System.Globalization.CultureInfo, System.Version, Boolean, System.Threading.StackCrawlMark ByRef)}
WatsonBuckets: null
_HResult: -2147024894
_className: null
_data: {System.Collections.ListDictionaryInternal}
_dynamicMethods: null
_exceptionMethod: {System.Reflection.RuntimeAssembly InternalGetSatelliteAssembly(System.String, System.Globalization.CultureInfo, System.Version, Boolean, System.Threading.StackCrawlMark ByRef)}
_exceptionMethodString: null
_fileName: null
_fusionLog: null
_helpURL: null
_innerException: null
_ipForWatsonBuckets: {1858045768}
_maybeFullPath: null
_message: "Could not find file 'AspNet5Beta8Resource.LegacyResources.resources'."
_remoteStackIndex: 0
_remoteStackTraceString: null
_safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
_source: "mscorlib"
_stackTrace: {sbyte[192]}
_stackTraceString: null
_watsonBuckets: null
_xcode: -532462766

_xptrs: {0}

**Comment by hishamco** [comment] 2015-10-20 14:20
@luchen1021 you need to build the LegacyLibrary to produce the assembly which will be located in **AspNet5Beta8Resource\AspNet5Beta8Resource.LegacyLibrary\bin\Debug**, after that you can run using ```dnx web```
It works fine in my end, problem solved :smile:

**Comment by luchen1021** [comment] 2015-10-20 15:20
Thank you for your help.  I got this error when using Visual Studio 2015 IDE to debug the solution.  I used both IIS Express and web as host option.  Both had the same exception.  Can you give some more detailed steps on using command dnx web, can I debug the solution using command dnx web?  Thanks again.

**Comment by hishamco** [comment] 2015-10-20 15:46
@luchen1021 Also you will get it when you run the application from command line, but whenever you build the class library your sample will work fine.
To run your app using command line do the following steps:
1- Open your web folder which **DnxWebHost** in your case
2- Right click the mouse while holding the shift key and choose open command window here
3- Run ```dnu restore``` command to restore all the packages that you application needs
4- Run ```dnx web``` command to run your web application and open the link which provided in your browser
Regarding the debugging, frankly I don't know, because I tried many times using Visual Code but what i notice it has ability to debug javaScript, perhaps it's under development

**Comment by luchen1021** [comment] 2015-10-20 19:53
Based on sample code https://github.com/aspnet/dnx/blob/dev/misc/ResourcesTestProjects/ReadFromResources/src/ReadFromResources/Program.cs, I have to change the following line of code in generated Resources.Designer.cs by Visual Studio from

	global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNet5Beta8LegacyLibrary.LegacyLibrary.Ext.Properties.Resources", typeof(Resources).Assembly);
		
To

	global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNet5Beta8LegacyLibrary.LegacyLibrary.Ext.Properties.Resources", System.Reflection.Assembly.Load(typeof(Resources).Assembly.GetName()));
	
Even the System.Reflection.Assembly.Load(typeof(Resources).FullName) does not work, has to be System.Reflection.Assembly.Load(typeof(Resources).Assembly.GetName()).

Is this by design?  If so, how do we work around the issue with existing satallite resource assembly, which always use typeof(Resources).Assembly instead of System.Reflection.Assembly.Load(typeof(Resources).Assembly.GetName())?

Thank you.

**Comment by leak** [comment] 2015-10-21 13:58
Same exception here. I added a non-DNX 3rd party DLL to a DNX class lib.

I cannot really follow the workaround above because I neither have any Designer files in my solution nor resources of my own (only the 3rd party lib is using resources for localization)

**Comment by kirthik** [comment] 2015-10-22 17:56
Thank you for reporting this issue. This seems like something we need to look at but the issue is filed in wrong repo. I filed a new bug in DNX repo - https://github.com/aspnet/dnx/issues/3047. Closing this one.

**Closed by kirthik** 2015-10-22 17:56 UTC
Labels: investigate
