### ISSUE TITLE
Localization always returns english clulture

### ISSUE THREAD

**Issue by ajtowf** [aspnet/Localization#293] opened 2016-10-02 12:45 UTC
My views contains swedish text e.g.
@Localizer["Välkommen"] // means welcome

If I have a english resource for my view e.g. Index.en.resx this text will get translated to the english text no matter what! Even if I configure the app not to even support english, eg:

```
services.Configure<RequestLocalizationOptions>(options =>
        {
            var supportedCultures = new[]
            {
                new CultureInfo("sv"),
                //new CultureInfo("en")
            };

            options.DefaultRequestCulture = new RequestCulture(culture: "sv", uiCulture: "sv");
            options.SupportedCultures = supportedCultures;
            options.SupportedUICultures = supportedCultures;
            options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(context =>
            {
                return Task.FromResult(new ProviderCultureResult("sv", "sv"));
            }));
        });
```

and in configure app:

```
var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
        app.UseRequestLocalization(locOptions.Value);
```

Pretty frustrating, so the workaround for now is to simply rename the resource files to some other culture, norweigan for instance e.g. Index.no.resx.

**Comment by hishamco** [comment] 2016-10-02 13:24
I configure the localization options like this, but the configuration that you did should work too. To make things work as expected you should add a Swedish resource file like the following **Resources/Views/ControllerName/ViewName.sv.resx**

**Comment by ajtowf** [comment] 2016-10-04 12:02
What you're proposing is something entirely different. My views contains Swedish text so there is no .sv.resx files since Swedish is the default. The user may choose to switch to English however, and if there is any ViewName.**en**.resx files, the text will be localized to English no matter what. See the difference?

**Comment by ajtowf** [comment] 2016-10-04 12:04
My workaround for this is to put the English localization into some bogus language like Norwegian e.g. ViewName.**no**.resx and camouflage Norwegian as English.

**Comment by hishamco** [comment] 2016-10-10 07:31
@ajtowf can you update to the latest version, I tried to use the localization sample with English & Swedish as supported cultures, Swedish is the default one. I added Startup.en.resx, so when I visit `http://localhost:5000` it retrieve **"Välkommen"**, when I visit `http://localhost:5000/?culture=en&ui-culture=en' I got **"Welcome"**, these are the correct and expected result.
If i'm not wrong it was bug, because I saw a similar result like what you mentioned before I update to the latest changes

**Comment by ryanbrandenburg** [comment] 2016-10-10 18:14
@ajtowf it doesn't sound like this is your issue, but as a warning it is generally a bad idea to rely on the behavior of your "default" language (that is, the one which "*.resx" instead of "*.lng.resx") without manually setting that language as described [here](https://github.com/aspnet/Localization/issues/277#issuecomment-246854009). Without setting that one way or another if you deploy to an English EC2 instance after developing in Swedish you will get the wrong language out of your default language.

That said, it sounds as if you're having a different issue. Once you've ensured you have the latest versions of MVC and localization as @hishamco suggested, if you're still having trouble I think the next step would be for you to provide a reproduction repo for us to troubleshoot against. Since our samples don't have this problem it's likely an edge case or configuration problem that won't be apparently until we can run your app.

**Comment by ajtowf** [comment] 2016-10-10 20:59
@ryanbrandenburg so my default language isn't in .resx, it's in the views, I only have *lang*.resx for non-default languages, e.g in Index.cshtml:

    @Localizer["Hej hej, hemskt mycket hej!"] 

will have a corresponding Index.en.resx that contains

    Hej hej hemst mycket hej! -> Hello Hello, very much hello!

i _won't_ have a Index.resx.

as recommended in https://docs.asp.net/en/latest/fundamentals/localization.html is that bad? Or am I missing something fundamental?

Also the user is allowed the change the lang by clicking links which will set the preffered lang in a cookie as described in the docs. Isn't that safe if we've specified the default request culture? Very confusing if not.

I'll try to update the versions and see if the problem still exists.

**Comment by ryanbrandenburg** [comment] 2016-10-10 21:53
If you have no "base" resx then ignore my first paragraph as it's irrelevant to you.

Setting a default request culture should have no bearing on the ability to use the [CookieRequestCultureProvider](https://github.com/aspnet/Localization/blob/861ae52de51f174e14701d6cdbb88e6543638b03/src/Microsoft.AspNetCore.Localization/CookieRequestCultureProvider.cs). I note that you had a `CustomRequestCultureProvider` in you snippet, which would cause you to always get Swedish as the request culture, but I assume that was added for testing purposes.

**Comment by ajtowf** [comment] 2016-10-11 19:24
@ryanbrandenburg yes the custom provider is just to illustrate that it doesn't matter what the user "chooses" it's always english. Same problem with latest versions, I'll create a sample repo to reproduce the bug.

By the way the samples don't suffer from this since the default language is english and it's possible to switch to french.

I'll get back with a sample app, thanks!

**Comment by ajtowf** [comment] 2016-10-11 19:59
@ryanbrandenburg @hishamco simple minimalistic repo to reproduce the bug https://github.com/ajtowf/LocalizationBug/

Maybe @DamianEdwards is interested?

**Comment by boindiil** [comment] 2016-10-12 11:05
I have exactly the same problem. 

I have implemented my own _RequestCultureProvider_, but the returned culture is ignored by the _IStringLocalizer_. However, it is used by _AnnotationsLocalization_ so my annotations are translated correctly.

I have basically the same setup as provided in the example of @ajtowf

**Comment by ryanbrandenburg** [comment] 2016-10-12 23:41
@ajtowf this was an interesting one! I was finally able to replicate this behavior by renaming a resource file from one language to another. When you look in the bin directory after doing that you'll see the folder for your new language, but you'll also still see the folder for the language that no longer has any resx files.  

More generally this is to say that language folders (and their discovery by dotnet) won't go away unless you 1) delete the language folder or entire bin directory 2) overwrite them with a new resource.

This is known behavior of the [cli](https://github.com/dotnet/cli/issues/2855). Can you delete the bin and obj directories of your project and confirm that fixes it for you?

**Comment by hishamco** [comment] 2016-10-13 05:19
That's the idea I want to suggest 😄

**Comment by ajtowf** [comment] 2016-10-13 07:39
@ryanbrandenburg so you mean by simply cloning my repo you get Swedish and not English when passing ?culture=sv as query param? @hishamco same for you? Why would I want to rename the resource files? I have English resources, that's correct. I'd say what you are suggesting is something entirely different.

Just to make myself clear again, my claim is that if you have an "en" folder, which contains the English localization that one will _always_ get served. There is no need for renaming any resource files to any other language and then deleting the old ones, that's not relevant. 

![image](https://cloud.githubusercontent.com/assets/3427270/19339836/14f4cc6c-9126-11e6-835b-a5fbd23d6122.png)

By simply having a English localization one would expect it not to be served when browsing the default Swedish localization.

**Comment by ajtowf** [comment] 2016-10-13 07:56
Isn't this the same thing as https://github.com/aspnet/Home/issues/1707 ? I see you've been active there as well @ryanbrandenburg

**Comment by ajtowf** [comment] 2016-10-13 08:08
Just verified this is only a problem when targeting framework netcoreapp1.0, works for full net451, just updated (the sample repo)[https://github.com/ajtowf/LocalizationBug/], it's obvious this is a bug, try switching between full and core framework.

@davidfowl I've seen you've been involved in other threads, care to comment? ;-)

**Comment by davidfowl** [comment] 2016-10-13 08:12
You need to use .NET >= 4.6 to get the behavior you want.

**Comment by ajtowf** [comment] 2016-10-13 08:17
@davidfowl thx for answering mate. 
Right, so this won't be possible targeting core at all? 
How can this not be a bug?

**Comment by davidfowl** [comment] 2016-10-13 08:18
Oh wait, I misread that, I thought it did work with core and *not* on .NET Framework.

**Comment by ajtowf** [comment] 2016-10-13 08:23
@davidfowl it would just be nice if this would be recognized as a bug, imho the [sample repo](https://github.com/ajtowf/LocalizationBug/) to reproduce must be enough. I keep getting suggestions in this thread that's completely irrelevant, it's getting ridiculous.

**Comment by khellang** [comment] 2016-10-13 09:22
> some bogus language like Norwegian

Heyyy! :angry:

**Comment by ajtowf** [comment] 2016-10-13 11:04
@khellang sorry mate, no offence, I'm a swede btw, sorry to hear about Johaug! ;-)

**Comment by khellang** [comment] 2016-10-13 11:31
Heh. Just trolling :wink: Yeah, "sorry" :stuck_out_tongue_closed_eyes: #SorryNotSorry

**Comment by ryanbrandenburg** [comment] 2016-10-13 18:13
@ajtowf sorry for any confusion, I was saying that renaming your resource files is a way to have a problem like this, not suggesting that you rename it as a solution. It IS true that renaming your resource files can give you these problems (regardless of framework) but after reading your most recent post I found that you are correct that it's not the problem you're running into.

Though the resultant description of behavior is the same as aspnet/Home#1707 they are not the same root cause, since in both your reproduction app and the more minimal one I've created the language directories are copied over.

I was able to replicate your problem reliably on netcoreapp and narrowed it down to a change in behavior in `ResourceManager`. I've created an issue against corefx [here](dotnet/corefx#12625).

Unfortunatly while we're waiting on the corefx team to resolve this issue the only ways I can see to avoid this problem are to use "bogus" languages like you have, or to not use `netcoreapp`, which are both less than ideal.

**Comment by ajtowf** [comment] 2016-10-13 19:34
@ryanbrandenburg cool, thx mate, I guess I'll go with the "awesome-other-language"-workaround (@khellang) for now until it's fixed and keep an eye on the issue you created. Feel free to close this bug, I don't know what your practices are for handling issues.

**Comment by hishamco** [comment] 2016-10-13 23:08
@ryanbrandenburg can you please fix the link of the corefx issue to https://github.com/dotnet/corefx/issues/12625

**Comment by ryanbrandenburg** [comment] 2016-10-13 23:10
Thanks @hishamco.

**Comment by Eilon** [comment] 2016-11-08 22:46
Moving to 1.2.0 per the email discussion.

**Comment by wc-matteo** [comment] 2017-01-19 16:18
Same problem... very frustrating seeing that the [official docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) make it clear that this scenario is not only supported, but advised: 

> We anticipate that many developers will **not** create a default language resource file.

<sup>(emphasis **not** mine)</sup>

> If you want to just return the key when missing a resource for the requested culture you must not have a default resource file.

Should be changed to:

> If you want to just return the key when missing a resource for the requested culture you must not have a default resource file. **At the moment, a resource file with an ".en" (or ".en-US") culture designator is considered a default resource file.**

The issue is that in .NET Core it ultimately falls back to the _Invariant Culture_, which is _en-US_.

This makes translating web apps (where the language of the keys is not english) more cumbersome. Now you have to create a resource file for the strings that you are _already_ using as keys.

**Comment by ajtowf** [comment] 2017-01-21 20:27
@wc-matteo you wouldn't believe how much time I've spent discussing this, just check out this thread https://github.com/dotnet/corefx/issues/12625, the discussion with tarekgh and gkhanna79 is mind blowing. Let's hope we get a fix soon, I wouldn't hold my breath though...

**Comment by wildsylvan** [comment] 2017-01-21 20:40
@ajtowf yep, I saw that thread... at least @ramarag [nailed ](https://github.com/dotnet/corefx/issues/12625#issuecomment-257446823)the issue... let's hope...

**Comment by wc-matteo** [comment] 2017-01-21 20:42
@ajtowf yep, I saw that thread... at least @ramarag nailed the [issue](https://github.com/dotnet/corefx/issues/12625#issuecomment-257446823)... let's hope...

**Comment by Ponant** [comment] 2017-01-30 10:21
@ajtowf @ryanbrandenburg @hishamco , same problem here in VS 2017 RC Asp.Net Core 1.1. This is a very nice bug. The statements made in the docs are incorrect and lead to the confusion in my opinion; it would be better to clarify that this is not 2-way (en or OS language->sv vs sv->en or OS anguage) until the issue is cleared.

**Comment by ryanbrandenburg** [comment] 2017-03-03 01:12
Fixed by #333.

**Closed by ryanbrandenburg** 2017-03-03 01:12 UTC
Labels: 3 - Done, blocked, task
