### ISSUE TITLE
Localizer don't work on Linux

### ISSUE THREAD

**Issue by linflux** [aspnet/Localization#314] opened 2017-01-18 19:28 UTC
I have an ASP.NET Core Web API (version 1.1) with use of Resources files for Localization/Globalization like [Microsoft Docs ASP.NET Core - Globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) explains.
On Windows it runs OK, but in Linux (via Docker local) the resources are not found.

Like the article used in the docs article, [Localization.StarterWeb project](https://github.com/aspnet/entropy).
I clone the repo from that repository, create a dockerfile, build and run.

Looks like the issue is on the Controller with IStringLocalizer because in Views (not my Web API case) the localizer works partially, like you see on images above.

![localizantio starterweb-about-onwindows10](https://cloud.githubusercontent.com/assets/2443704/22078908/e9c5397e-dda0-11e6-8614-78aaa3026d61.PNG)
### Running on Windows 10. ###

![localizantio starterweb-about-ondockerlinux](https://cloud.githubusercontent.com/assets/2443704/22078973/43e0ef16-dda1-11e6-8204-f3cefdbe4c8b.PNG)
### Running on Linux Docker. ###
**Repair the second message get from controller was not localized to French.**

The dockerfile used to run this app.
```Dockerfile

FROM microsoft/dotnet:latest

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore"]

RUN ["dotnet", "build"]

EXPOSE 5000

CMD ["dotnet", "run", "--server.urls", "http://*:5000"]
```

I inspect this StringLocalizer object and on Windows that's the result:
```javascript
{"messageToString":"Votre page de description de l'application .",
"msg":{
"name":"Your application description page.",
"value":"Votre page de description de l'application .",
"resourceNotFound":false}}
```
The inspect of StringLocalizer on Linux:
```javascript
{"messageToString":"Your application description page.",
"msg":{
"name":"Your application description page.",
"value":"Your application description page.",
"resourceNotFound":true}}
```

I don't know why this resourceNotFound are true on Linux, don't have any clue, the DLL files are generated. I don't know where the problem is, have no idea.

The same thing occurs with my Web API application.
For now, I just go move to a static dictionary class workaround while this issue is not fixed.

**Comment by hishamco** [comment] 2017-01-19 01:08
@glennc you're the only one who I know on Docker, could you please check this or assign it to the right person, unfortunately I don't have a Linux installed or I will check it myself

**Comment by Eilon** [comment] 2017-02-23 17:34
@ryanbrandenburg can you take a look? You can have @glennc help you out with Docker stuff, if needed.

@linflux in the meantime, I'm wondering if maybe there's a casing issue somewhere? Maybe some mixed uppercase/lowercase that works on Windows, but not on Linux?

**Comment by hishamco** [comment] 2017-02-23 17:48
@linflux it will be nice if you share the repo that you working with, perhaps it's a casing issue as @Eilon mentioned before

**Comment by linflux** [comment] 2017-02-23 20:45
@Eilon @hishamco I created a repo, links down below:
https://github.com/linflux/localizationdotnetcore

**Comment by hishamco** [comment] 2017-02-23 21:52
@linflux why you are using `IStringLocalizer` in the controller https://github.com/linflux/localizationdotnetcore/blob/1cae51b7d9d2aac985869d9f5ab59697aae8064d/Controllers/HomeController.cs#L16 while you injecting the `IViewLocalizer` in the view https://github.com/linflux/localizationdotnetcore/blob/1cae51b7d9d2aac985869d9f5ab59697aae8064d/Views/Home/About.cshtml#L3

**Comment by linflux** [comment] 2017-02-23 22:13
I don't know just came from the microsoft sample as you can see here:
https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Controllers/HomeController.cs#L16
And here:
https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Views/Home/About.cshtml#L3

But on my work project Web API i just only use IStringLocalizer and don't work too.

**Comment by hishamco** [comment] 2017-02-23 22:32
I see, could you please check if this issue occurs with Localization.StarterWeb, if it is could be a bug, also the other guys may look to it. Unfortunately I don't have a Linux, but I was trying to figure out if there's something else causes this issue

**Comment by linflux** [comment] 2017-02-23 22:44
Yes, it occurs too. That's why I look for a sample for check if the problem is just in my work API code.
I also don't have Linux installed in this machine, i run on docker. You should try it! It seems like a monster at first but it's not so complicated. I think like a VM without GUI. I know is more than that. 
https://docs.docker.com/docker-for-windows/install/

**Comment by ryanbrandenburg** [comment] 2017-02-24 20:52
@linflux this appears to be a problem of namespaces. When you copied this code from Localization.StarterWeb you left the namespace intact in all your *.cs files as `Localization.StarterWeb`. That's fine if you leave the project in a folder named `Localization.StarterWeb` but when cloning your localizationdotnetcore repo the code will end up in a folder named `localizationdotnetcore`, and since in project.json your assembly name defaults to the name of the folder holding the project.json your resources are now wrong. You can avoid this problem by including 
```
{
  "name": "Localization.StarterWeb"
}
```
in your project.json to make the assembly name explicit. See [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) for the documentation on this.

**Comment by ryanbrandenburg** [comment] 2017-03-03 20:29
Seems that may have fixed it, let us know if not.

**Closed** 2017-03-03 20:28 UTC
Labels: investigate

**Comment by TsengSR** [comment] 2017-07-26 12:49
This stuff is really a pain in the butt. 

I had it working fine, when it was in the main assembly, but once I moved the controllers to their own assembly, localization isn't working. 

Project.Name.WebApi << main project
Project.OtherName.Mvc << Controllers of a specific modules, i.e. related to orders

In `Project.OtherName.Mvc` I got a "Resources" folder with `SharedResources.de-DE.resx`.

```
    // Startup.cs
    services.AddLocalization(options => options.ResourcesPath = "Resources");
    var localizationOptions = new RequestLocalizationOptions
    {
        SupportedCultures = new List<CultureInfo>
        {
            new CultureInfo("de-DE"),
            new CultureInfo("en-US"),
            new CultureInfo("en-GB")
        },
        SupportedUICultures = new List<CultureInfo>
        {
            new CultureInfo("de-DE"),
            new CultureInfo("en-US"),
            new CultureInfo("en-GB")
        },
        DefaultRequestCulture = new RequestCulture("de-DE")
    };

    localizationOptions.RequestCultureProviders.Insert(0, new UrlRequestCultureProvider
    {
        Options = localizationOptions
    });
```

```
namespace Project.OtherName
    public class SharedResource
    {
    }
}
```

Neither of the following is working: 

* `namespace Project.OtherName` and `SharedResources.de-DE.resx`.
* `namespace Project.OtherName` and `Project.OtherName.SharedResources.de-DE.resx`.
* `namespace Project.OtherName.Mvc` and `SharedResources.de-DE.resx`.
* `namespace Project.OtherName.Mvc` and `Project.OtherName.Mvc.SharedResources.de-DE.resx`.

neither it's working when the Resources are located in the `Project.Name.WebApi` assembly and the `SharedResources` class in the `Project.Othername.Mvc` assembly.

Would be **awesome** if someone could post a working sample which uses satellite assemblies with controllers in it.

**Comment by Eilon** [comment] 2017-07-26 23:35
@TsengSR sorry you're running into problems with this. Can you post a new issue, and ideally a sample app that shows the problem, and we will investigate? Once we get to the bottom of this we can make sure the documentation is updated with the correct info.

**Comment by TsengSR** [comment] 2017-07-27 10:57
@Eilon: Ok I opened a new issue (#398) with some more details when it happened and the observations I made during creating this reproduction.
