### ISSUE TITLE
MVC 6 / Asp.net VNEXT how to use shared, separate Resource DLL with IViewLocalizer or IHtmlLocalizer and .resx

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#246] opened 2016-05-24 07:21 UTC
Moved from https://github.com/aspnet/Mvc/issues/4723
Opened by @MrWinky

----------------
There are lots of great VNEXT articles explaining how to use RESX resources when the \Resources folder are in the VNEXT  application's sub folder path.   

However, I have an MVC application which requires I place the RESX files in a separate VNEXT class library dll in the solution and share it among projects (assume the separate project is called MyResourceProject).   Maybe I should be using a different project type for sharing resource strings in a  RESX?

The following does not work:

```c#
 services.AddLocalization(options => options.ResourcesPath = "MyResourceProject .Resources");
```

and

```c#
  services.AddMvc()
          .AddViewLocalization(options => options.ResourcesPath = "MyResourceProject .Resources")
```

How do I point to a separate library path in an MVC VNEXT application?

**Comment by Eilon** [comment] 2016-05-24 07:22
Possibly related: https://github.com/aspnet/Localization/issues/214

**Comment by MrWinky** [comment] 2016-05-24 13:46
In 214,   I am not seeing a solution.   The problem is when I design a 3 tiered application this issue causes a circular reference.   The main web portal module suddenly becomes a dependency to the Data and Business layer modules.

For example:

1.   EF 7 is kept in it's own project.  MyProject.Data.EntityFramework
2.  Business logic layer objects which use the strings  MyProject.BLL.ViewModels
2.  The web portal (with startup.cs) is in it's own project MyProject.Portal

This is pretty standard N tier architecture.   

Each of these projects need the resx files.   

However,   If I am forced to place  MyProject.Resources.resx in the web portal app, now I have a circular reference problem.   Because Portal project is dependent on  EntityFramework and ViewModel projects (as it should be).   Conversely,  EntityFramework and BLL need those SAME resource strings and now becomes dependent on the Portal project!?.

**Comment by ryanbrandenburg** [comment] 2016-09-28 18:15
@MrWinky we did the work to allow class library resources in #283. To enable this scenario you need to add `ResourceLocationAttribute` to the AssemblyInfo of the class libraries so that the "main" project knows where to look for the resources.

Let us know if you have any trouble with that, or if I misunderstood and that doesn't actually resolve your issue.

**Comment by ryanbrandenburg** [comment] 2016-09-28 23:08
On second thought I'll close this as it seems to be the exact use case #283, but feel free to re-open if the need arises.

**Closed by ryanbrandenburg** 2016-09-28 23:08 UTC
Labels: 2 - Working

**Comment by fabercs** [comment] 2018-11-19 06:20
> @MrWinky we did the work to allow class library resources in #283. To enable this scenario you need to add `ResourceLocationAttribute` to the AssemblyInfo of the class libraries so that the "main" project knows where to look for the resources.

hi @ryanbrandenburg, could you please elaborate this answer? You say `AssemblyInfo` of the class librarie**s**. Which libraries? Where exactly to put the attribute?

**Comment by hishamco** [comment] 2018-11-19 13:08
@fabercs you should decorate your assembly by adding `ResourceLocationAttribute` to the `AssemblyInfo`. Have a look to this line for instance https://github.com/aspnet/Localization/blob/master/test/ResourcesClassLibraryWithAttribute/AssemblyInfo.cs#L7

**Comment by fabercs** [comment] 2018-11-19 13:33
@hishamco thank you for answer, this is my solution structure;
```
|--MyProject.Infrastructure
|--MyProject.Core
|--MyProject.Web
    |--Controllers
    |--ViewModels
    |--Views
|--MyProject.Resources
    |--Controllers
    |--ViewModels
    |--Views
```
Should I create an `AssemblyInfo.cs` file under `MyProject.Resources`  and add the line `[assembly: ResourceLocation("ResourceFolder")]`? Should I wrap all the files in a `ResourceFolder` or keep it as is?

**Comment by hishamco** [comment] 2018-11-19 14:03
Yep, add it under `MyProject.Resources`

> Should I wrap all the files in a ResourceFolder or keep it as is

Yes & No, but the important thing is resource naming, you can check the docs on this one

**Comment by hishamco** [comment] 2018-11-22 09:05
@fabercs seems this issue is died, could you please file a new issue in the [AspNetCore](https://www.github.com/aspnet/AspNetCore) repo and copy your latest comment

**Comment by fabercs** [comment] 2018-11-22 10:21
@hishamco actually I have already created a new issue, https://github.com/aspnet/Mvc/issues/8739
I have also moved my last comment to there..

**Comment by hishamco** [comment] 2018-11-22 11:36
That's great, waiting for your reply there
