### ISSUE TITLE
Custom Culture Resource file

### ISSUE THREAD

**Issue by IvanCisneros** [aspnet/Localization#270] opened 2016-08-02 21:01 UTC
Hi,

I have created some custom cultures and also added the resources files for those custom cultures, but when running the application the resources for the custom cultures are not being found, translations for valid cultures like es-MX, en-US are found. i Have added the custom cultures in the supported cultures list on startup.

I notice that on my bin folder, theres a folder for every culture but in there just appears the valid ones not the custom ones.

Do custom cultures are not supported on ASP CORE yet?

**Comment by hishamco** [comment] 2016-08-02 22:09
What you mean by custom culture? If the culture is supported by the OS, it should work as expected

**Comment by IvanCisneros** [comment] 2016-08-02 22:17
I have created custom cultures like fr-PF (french - french Polynesia), among others, i have register the cultures using cultureAndRegionInfoBuilder.Register(),

I added the culture in supportedCultures at startup, im using IViewLocalizer and its working for no custom cultures, but for the ones i register its not working, when deploying i see that folders with the culture name are being create it, inside theres a dll with the name of the project, but im not seeing these folders for my custom cultures (fr-PF, es-AW,etc)

**Comment by hishamco** [comment] 2016-08-02 22:33
I didn't try cultureAndRegionInfoBuilder.Register before, AFAIK if the culture is not supported by the OS, it will fallback to the default one. May be it's a runtime issue, @ryanbrandenburg any idea?

**Comment by Eilon** [comment] 2016-08-03 16:59
@IvanCisneros which OS is it? Not sure it matters these days, but at least in some points in the past the native OS had to also have the culture registered. But it could certainly help us reproduce the issue.

**Comment by IvanCisneros** [comment] 2016-08-03 17:05
@Eilon  im using Windows 7 Professional, another thing i found its that when adding the resources to the project, only for the resources of my custom cultures a designer cs file was create it.

**Comment by Eilon** [comment] 2016-08-04 17:37
@IvanCisneros thanks for the info, we will investigate.

**Comment by ryanbrandenburg** [comment] 2016-08-10 23:32
@IvanCisneros could you upload a repro app to Github? Also, what version of System.Globalization are you using? Because I don't see `CultureInfAndRegionInfoBuilder` on 4.0.11.

**Comment by IvanCisneros** [comment] 2016-08-11 14:58
@ryanbrandenburg I believe its 4.0.1, will try to upload an example of the project.

as a note, I can see my custom cultures registed on control panel Region and Language section, they appear with an asterisk at the end and im not getting any errors when changing the culture in my application to those custom cultures but the resources files are not found.

This is what i notice so far:

- Only for my custom cultures resources files a designer cs file was created

-  When debuging or publishing i see that a folder with the culture name its created (ex. en-US,es-MX) and inside theres a dll with the name of my project, except these folders are not created for my custom cultures.

- When debuging i saw a Obj folder being created, inside theres debug\net461 folders and i can see the resources for my custom cultures, they have the .resources extension (only the resources of my custom cultures appear here) along with these files theres dotnet-compile.rsp, dotnet.assemblyinfo.cs, etc.

Hope that information could be useful.

Thanks

**Comment by ryanbrandenburg** [comment] 2016-08-16 18:44
You do appear to be correct, though it seems to be a problem with the CLI rather than with Localization. I've filed issue dotnet/cli/issues/4050 against them.

**Comment by IvanCisneros** [comment] 2016-08-17 17:45
@ryanbrandenburg Thanks for the support, will follow up the open bug. Thanks

**Comment by Eilon** [comment] 2016-09-11 23:52
@ryanbrandenburg any further action required for this bug?

**Comment by ryanbrandenburg** [comment] 2016-09-12 16:59
True, I'll close this one in favor of the CLI bug.

**Closed by ryanbrandenburg** 2016-09-12 16:59 UTC
Labels: 1 - Ready, blocked, investigate
