### ISSUE TITLE
Localization functional tests don't run on desktop

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Localization#390] opened 2017-06-29 15:34 UTC
We missed updating the test runner (https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs#L57). Consequently the tests run on desktop and coreclr but deploy the tests for netcoreapp2.0.

An alternative we can consider is to use TestHost instead. We're not really testing the deployment or server behavior here, so an in-memory host should be just as good and significantly faster.

**Comment by hishamco** [comment] 2017-06-29 16:50
I think this is a duplicate of issue #360

**Comment by pranavkm** [comment] 2017-06-29 16:53
@hishamco not necessarily. It's important that we actually run the tests on desktop. How we achieve it is sort of tangential.

**Comment by hishamco** [comment] 2017-06-29 16:57
> It's important that we actually run the tests on desktop

I see, but how the CI doesn't failed when it runs the functional test?!!

**Comment by pranavkm** [comment] 2017-06-29 17:33
@hishamco it's deploying netcoreapp2.0 twice (rather than deploying `netcoreapp2.0` once and `net461` the other time).

**Closed** 2017-08-09 17:25 UTC
Labels: 2 - Working, task
