### ISSUE TITLE
Data annotations localization on models in separate class library doesn't work

### ISSUE THREAD

**Issue by devharis** [aspnet/Localization#267] opened 2016-07-28 12:19 UTC
I've been implementing localization with success on Views/Controllers and got stuck on implementing localization on data annotations using .resx files. I don't seem to make it work at all. The [documentation ](https://docs.asp.net/en/latest/fundamentals/localization.html#dataannotations-localization) is pretty shy on that part as it only describes how to implement it on ViewModels within the same project.

Startup.cs
        
    services.AddLocalization();

    services.AddMvc()
     .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix, options => options.ResourcesPath = "Resources")
     .AddDataAnnotationsLocalization();`

Would be awesome if it was possible to add `options => options.ResourcesPath = "Resources"` on `.AddDataAnnotationsLocalization()` and specify path to separate project.

I'm pretty eager and desperate to know how I could solve this? Is it not possible yet?

**Comment by devharis** [comment] 2016-07-28 15:32
Added separate Resource folder in the class library and added this
 `  "buildOptions": {
    "embed": [
      "Resources/**"
    ]
  },`

Also implemented a custom StringLocalizer, StringLocalizerFactory, no success. Still same output, no translation.

**Comment by hishamco** [comment] 2016-07-28 17:18
@devharis AFAIK there's an issue in localization in when you use it in class library, have a look to this PR #265. @ryanbrandenburg correct me if I'm wrong

**Comment by Eilon** [comment] 2016-07-28 17:42
@hishamco yeah I think you're right.

@ryanbrandenburg can you confirm if this is essentially a dup?

**Comment by devharis** [comment] 2016-07-28 17:42
Thanks for the heads up @hishamco. I just recently managed to implement a work around with custom localizers. Phew!

**Comment by ryanbrandenburg** [comment] 2016-07-28 22:56
Yes, this is a duplicate of #157.  @devharis writing a custom Localizer/LocalizerFactory as you did is likely going to be our advice for people who need this going forward. Unfortunately we don't have any way to know what ResourcePath each class library will be using, so it's impossible in general to construct the resource names that will be needed. This isn't a scenario we had planned to support, but I am doing some work to make it easier to subclass `ResourceManagerStringLocalizerFactory` in ways that can meet people's bespoke needs without them needed to understand the nitty-gritty of Resource naming inside the satellite assemblies.

On that note I'm closing this out, follow #157 for more info.

**Closed by ryanbrandenburg** 2016-07-28 22:56 UTC
Labels: investigate
